name: End-to-end tests
on: push
jobs:
    cypress-run:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            # Install npm dependencies, cache them correctly
            # and run all Cypress tests
            - name: Install system dependencies
              run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
            - name: Cypress run
              uses: cypress-io/github-action@v6
