name: Run Cypress Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout code từ repository
            - name: Checkout code
              uses: actions/checkout@v4

            # 2. Thiết lập Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'

            # 3. Cài đặt dependencies
            - name: Install dependencies
              run: npm install

            # 4. Chạy Cypress tests
            - name: Run Cypress
              run: npx cypress run

            # 5. Lưu video và ảnh (tùy chọn)
            - name: Archive Cypress videos and screenshots
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-artifacts
                  path: |
                      cypress/videos/
                      cypress/screenshots/
